### ISSUE TITLE
What does Chan26.npy file each cloumn value represent? 

### ISSUE THREAD

**Issue by MohammedKhandwawala** [etsmit/seraproject#1]
Hello , I am working on RFI detection and mitigation and i went through your project. I need a RF telescope dataset. I am trying to produce results from the paper " Radio Frequency Interference Detection and Mitigation , Algorithms Based on Spectrogram Analysis".

**Comment by etsmit** [comment]
Chan26.npy is very deprecated by now. In general, the npy files associated with this project are in the shape (Nchannels, Nspectra, Npol)
